param()

# Fail on any error
$ErrorActionPreference = 'Stop'

# Fetch value to determine if workflow should deploy Azure Container Apps
$deployApps = azd env get-value DEPLOY_AZURE_CONTAINERAPPS

Write-Output "Database backend: horizondb"


# Deploys Frontend and Backend apps if the variable is set to "true"
if ($deployApps -eq 'true') {
    Write-Output "Deploying frontend and backend apps..."
    azd deploy
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    & "$PSScriptRoot/postdeploy.ps1"

}
else {
    Write-Output "Skipping application deployment as DEPLOY_AZURE_CONTAINERAPPS is set to 'false'."
}




# Fetch environment variables for managed identity setup
$deployHorizonDb            = azd env get-value DEPLOY_HORIZON_DB 2>$null
$deployOpenAI               = azd env get-value DEPLOY_AZURE_OPENAI 2>$null
$llmEndpoint                = azd env get-value AZURE_OPENAI_ENDPOINT
$llmApiVersion              = azd env get-value AZURE_OPENAI_API_VERSION
$embedApiVersion            = azd env get-value AZURE_OPENAI_API_VERSION_EMBED
$chatModel                  = azd env get-value AZURE_OPENAI_CHAT_MODEL
$chatDeployment             = azd env get-value AZURE_OPENAI_CHAT_DEPLOYMENT
$embedModel                 = azd env get-value AZURE_OPENAI_EMBED_MODEL
$embedDeployment            = azd env get-value AZURE_OPENAI_EMBED_DEPLOYMENT
$identityName               = azd env get-value SERVICE_BACKEND_IDENTITY_NAME
$arizeUri                   = azd env get-value SERVICE_ARIZE_URI 2>$null

# Build .env file — sections are commented out when the corresponding service is skipped
$dbHost  = azd env get-value POSTGRES_HOST
$dbName  = azd env get-value POSTGRES_DATABASE
$kvName  = azd env get-value AZURE_KEY_VAULT_NAME 2>$null

# Derive Phoenix/Arize endpoints from deployed arize service URI
if (-not [string]::IsNullOrWhiteSpace($arizeUri) -and $arizeUri -notlike 'ERROR:*') {
    $phoenixBaseUrl = $arizeUri.TrimEnd('/')
    $phoenixCollectorEndpoint = "$phoenixBaseUrl/v1/traces"
} else {
    $phoenixBaseUrl = 'http://localhost:6006'
    $phoenixCollectorEndpoint = 'http://localhost:6006/v1/traces'
}

if ($deployHorizonDb -eq 'false') {
    $dbSection = @"
# HorizonDB Connection (skipped)
# DB_HOST=
# DB_NAME=
# DB_PORT=5432
# DB_USER=
# DB_PASSWORD=
# DB_TYPE=horizondb
"@
} else {
    # Credentials are auto-generated by Bicep and stored in Key Vault
    $horizonUser = az keyvault secret show --vault-name $kvName --name 'db-user' --query value -o tsv 2>$null
    if ([string]::IsNullOrWhiteSpace($horizonUser)) { $horizonUser = 'horizonAdmin' }
    $horizonPass = az keyvault secret show --vault-name $kvName --name 'db-password' --query value -o tsv 2>$null

    $dbSection = @"
# Database Connection (HorizonDB — password auth)
DB_HOST=$dbHost
DB_NAME=$dbName
DB_PORT=5432
DB_USER=$horizonUser
DB_PASSWORD=$horizonPass
DB_TYPE=horizondb
"@
}

if ($deployOpenAI -eq 'false') {
    $openAISection = @"
# Azure OpenAI Configuration (skipped)
# AZURE_OPENAI_ENDPOINT=
# AZURE_OPENAI_CHAT_MODEL=
# AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=
# AZURE_OPENAI_EMBEDDING_MODEL=
# AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=
# AZURE_OPENAI_API_VERSION=
# AZURE_OPENAI_API_KEY=
"@
} else {
    # Fetch Azure OpenAI API key from Key Vault (do not log the value)
    $azureOpenAiKey = ''
    if (-not [string]::IsNullOrWhiteSpace($kvName)) {
        $azureOpenAiKey = az keyvault secret show --vault-name $kvName --name 'azure-openai-api-key' --query value -o tsv 2>$null
    }
    if (-not [string]::IsNullOrWhiteSpace($azureOpenAiKey)) {
        Write-Host "  ✓ AZURE_OPENAI_API_KEY fetched from Key Vault" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️  AZURE_OPENAI_API_KEY could not be retrieved from Key Vault" -ForegroundColor Yellow
    }

    $openAISection = @"
# OpenAI Configuration (Managed Identity Auth)
AZURE_OPENAI_ENDPOINT=$llmEndpoint
AZURE_OPENAI_CHAT_MODEL=$chatModel
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=$chatDeployment
AZURE_OPENAI_EMBEDDING_MODEL=$embedModel
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=$embedDeployment
AZURE_OPENAI_API_VERSION=$llmApiVersion
AZURE_OPENAI_API_KEY=$azureOpenAiKey
"@
}

@"
$dbSection

# Azure Identity (still used for OpenAI)
AZURE_IDENTITY_NAME=$identityName

$openAISection

# Application Configuration
APP_VERSION=0.1.0
ENVIRONMENT=local
CHAT_HISTORY_DB_TABLE_NAME=chat_history

# Seeding Configuration
SEC_FILES_SEEDING_BATCH_SIZE=200
NEWS_ARTICLES_SEEDING_BATCH_SIZE=200

# Vector Store Configuration
VECTOR_STORE_COLLECTION_NAME_SEC_FILINGS=sec_filings
VECTOR_STORE_COLLECTION_NAME_NEWS_ARTICLES=news_articles

# Query Configuration
STOCK_PRICE_DROP_THRESHOLD_PERCENTAGE=25
TOP_K_NEWS_ARTICLES=10
TOP_K_SEC_FILINGS=5

# Observability (Arize Phoenix)
PHOENIX_PROJECT_NAME=agentic-advisor
PHOENIX_COLLECTOR_ENDPOINT=$phoenixCollectorEndpoint
PHOENIX_BASE_URL=$phoenixBaseUrl
"@ | Out-File -FilePath .env -Encoding utf8
